# Prod: fetch from URL
mvn-arch.catalog.source=url
mvn-arch.catalog.url=https://raw.githubusercontent.com/sosuisen/mvn-arch-catalog/refs/heads/main/archetypes.json

# Suppress Quarkus banner and startup/shutdown logs
quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native image
quarkus.package.output-name=mvn-arch
quarkus.native.additional-build-args=--initialize-at-run-time=org.jline

# Dev: load from local file
%dev.mvn-arch.catalog.source=file
%dev.mvn-arch.catalog.local-path=archetypes.json
